spring:
  application:
    name: user-management-service
server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.1.5:8761/eureka