spring:
  application:
    name: user-management-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://localhost:8083/auth/realms/baeldung
          jwkSetUri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@192.168.1.5:8761/eureka
