spring:
  application:
    name: user-management-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://192.168.1.5:8083/auth/realms/baeldung
          jwkSetUri: http://192.168.1.5:8083/auth/realms/baeldung/protocol/openid-connect/certs
server:
  port: 8001
